In [ ]:
import numpy as np
import tensorflow as tf


In [ ]:
V = np.array([1,2,3,4])
V


array([1, 2, 3, 4])

In [ ]:
M= np.array([[1,2],[3,4],[5,6,],[7,8]])
M


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
T = tf.constant([[1,2]], dtype=tf.int32)
T

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>